[package]
name = "evaluator"
version = "0.1.0"
edition = "2021"

[dependencies]
async-process = "1.5.0"
async-std = { version = "1.12.0", features = ["attributes"] }
clap = { version = "4.0.22", features = ["derive", "env"] }
csv-async = "1.2.4"
futures = "0.3.28"
rustyline = "14"
ureq = "2.9.7"
urlencoding = "2.1.3"
