name: CI/CD Image dev

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-push-dev:
    name: Build and Push Docker Image :dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker

      - name: Set up Make
        run: sudo apt-get install -y make

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image :dev (monolith)
        run: make docker-build-dev

      - name: Push :dev to Docker Hub
        run: make docker-push-dev-hub

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Push :dev to personal GHCR
        run: make docker-push-dev-ghcr-personal

      - name: Push :dev to org GHCR
        run: make docker-push-dev-ghcr-itc
